### PR TITLE
Custom Icon prop added.

### PR DESCRIPTION
**Pull request by SankalpaFernando**
An icon prop has been added to the NotifyMe component

### CODE REVIEW

**Comment by atapas** [comment]
@SankalpaFernando Thanks for putting the PR. Could you please describe how did you test it?

**Comment by SankalpaFernando** [comment]
@atapas I did manual testing using a React App (create-react-app template)

**Comment by atapas** [comment]
> @atapas I did manual testing using a React App (create-react-app template)

Great, Possible to add a screenshot of the component with another icon?

**Comment by SankalpaFernando** [comment]
screenshot

**Comment by SankalpaFernando** [comment]
@atapas This is a screenshot by adding the react-feather icon BookOpen.

**Comment by atapas** [comment]
@SankalpaFernando 

Thanks a lot for taking the issue and making the app better. Please feel free to pick up more, contribute more. I wish you a great #Hactoberfest ahead. You will be added to the contribution list right after we merge this PR. Don't forget to share about your contribution publicly and provide your support with a star ⭐.

Great work 🔥 !!!!

**Review by atapas — APPROVED** [review]
Changes are looking good approving

**Comment by atapas** [comment]
@all-contributors please add @SankalpaFernando for Code

**Comment by SankalpaFernando** [comment]
@atapas Can you tag this as hactoberfest-accepted

**Comment by atapas** [comment]
> @atapas Can you tag this as hactoberfest-accepted

It's already been tagged

image

**Comment by SankalpaFernando** [comment]
Sorry, my bad. thanks.

**Pull request merged**
