### PR TITLE
Fixed typo for the word component in the README.md file.

### PR DESCRIPTION
**Pull request by donymvarkey**
Fixed the typo in the README file.

### CODE REVIEW

**Comment by atapas** [comment]
@donymvarkey 

Thanks a lot for taking the issue and making the app better. Please feel free to pick up more, contribute more. I wish you a great #Hactoberfest ahead. You will be added to the contribution list right after we merge this PR. Don't forget to share about your contribution publicly and provide your support with a star ⭐.

Great work 🔥 !!!!

**Review by atapas — APPROVED** [review]
Changes are looking good. Approving.

**Comment by atapas** [comment]
@all-contributors please add @donymvarkey  for Documentation

**Comment by donymvarkey** [comment]
Thanks for adding me to the Contributors list. Also i will be using this component in a project soon

**Pull request merged**
